# Generated by Django 3.0.7 on 2020-07-13 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=40)),
                ('employee_account', models.CharField(max_length=40)),
                ('employee_password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=40)),
                ('enterprise_account', models.CharField(max_length=20)),
                ('enterprise_password', models.CharField(max_length=40)),
                ('enterprise_address', models.CharField(default='address', max_length=80)),
                ('enterprise_tel', models.IntegerField(default=12345, verbose_name='telephone')),
                ('enterprise_mail', models.EmailField(default='mail', max_length=20)),
                ('enterprise_info', models.CharField(default='info', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_birthday', models.DateTimeField(default=django.utils.timezone.now, verbose_name='birthday')),
                ('resume_gender', models.CharField(choices=[('man', '男'), ('woman', '女')], default='man', max_length=6, verbose_name='gender')),
                ('resume_race', models.CharField(default='汉', max_length=4)),
                ('resume_school', models.CharField(default='school', max_length=40)),
                ('resume_degree', models.CharField(default='degree', max_length=40)),
                ('resume_major', models.CharField(default='major', max_length=40)),
                ('resume_tel', models.IntegerField(default=12345)),
                ('resume_mail', models.EmailField(default='mail', max_length=20)),
                ('resume_info', models.CharField(default='info', max_length=200)),
                ('resume_address', models.CharField(default='address', max_length=80)),
                ('resume_employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jmr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=40)),
                ('job_school', models.CharField(default='school', max_length=40)),
                ('job_degree', models.CharField(default='degree', max_length=40)),
                ('job_major', models.CharField(default='major', max_length=40)),
                ('job_salary', models.IntegerField(default=10000)),
                ('job_count', models.IntegerField(default=1)),
                ('job_info', models.CharField(default='info', max_length=200)),
                ('job_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmr.Enterprise')),
                ('job_resume', models.ManyToManyField(to='jmr.Resume')),
            ],
        ),
    ]
