# Generated by Django 3.0.7 on 2020-07-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplyee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=40)),
                ('employee_account', models.CharField(max_length=40)),
                ('employee_password', models.CharField(max_length=40)),
                ('employee_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=40)),
                ('enterprise_account', models.CharField(max_length=40)),
                ('enterprise_password', models.CharField(max_length=40)),
                ('enterprise_address', models.CharField(max_length=80)),
                ('enterprise_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=40)),
                ('job_school', models.CharField(max_length=40)),
                ('job_degree', models.CharField(max_length=40)),
                ('job_major', models.CharField(max_length=40)),
                ('job_salary', models.IntegerField()),
                ('job_count', models.IntegerField()),
                ('job_info', models.CharField(max_length=200)),
                ('job_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmr.Enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_school', models.CharField(max_length=40)),
                ('resume_degree', models.CharField(max_length=40)),
                ('resume_major', models.CharField(max_length=40)),
                ('resume_call', models.CharField(max_length=40)),
                ('resume_employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jmr.Emplyee')),
                ('resume_job', models.ManyToManyField(to='jmr.Job')),
            ],
        ),
    ]
