# Generated by Django 3.0.7 on 2020-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_mail',
            field=models.EmailField(default='1', max_length=254),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_tel',
            field=models.IntegerField(default=1),
        ),
    ]
