# Generated by Django 3.0.7 on 2020-07-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_resume',
            field=models.ManyToManyField(null=True, to='jmr.Resume'),
        ),
    ]
